# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  vmImage: ubuntu-latest

jobs: 
  - job:
    steps:
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Azure subscription 1(70b497ac-65bf-44a8-b460-fc7870d6d0ca)'
          appType: 'webAppLinux'
          WebAppName: 'localstore'
          deployToSlotOrASE: true
          ResourceGroupName: 'LucasResources'
          SlotName: 'production'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
          RuntimeStack: 'DOTNETCORE|6.0'
